### PR TITLE
fix(index.ts): add basename to manage relative paths

### LINKED ISSUE #1: Can't find HTML files if the outDir property has a relative path
Hi, with this configuration for the build:

```
  root: './src',
  base: '/',
.....
build: {
    outDir: '../dist',
    assetsDir: 'assets',
    emptyOutDir: true
  },
```
the plugin can't find any HTML files to read. 

At the end the plugin tries to read `glob('../dist/**/*.html', (err, files) => {` but the result is zero files.

### PR DESCRIPTION
**Pull request by felixzapata**
This pull request fixes #1

### CODE REVIEW

**Comment by zhuweiyou** [comment]
Assuming the `outDir: '../a/b'`,  `basename()` will get ` b`, not expected.

**Comment by felixzapata** [comment]
mmm maybe using `resolve` instead of `basename`

**Comment by zhuweiyou** [comment]
I have a better way to solve this problem and update it later.

**Comment by felixzapata** [comment]
ok, I will close the pull request in that case.

**Pull request closed without merging**
